package ws

import "testing"

// TestMBTDeflState replays the committed DEFLATE state-machine traces
// (model/gen, doc/DEFLATE-STREAM.md part 2) against a live RawConn with
// permessage-deflate negotiated. Same contract as TestMBTDeflate: the
// MUST protocol outcomes are asserted hard (the delivered payload, the
// terminal close codes), and the SHOULD / MAY layer of the RFC 7692
// silences (a truncated or non-compliant 7.2.1 wire that the
// implementation's completion tail repairs is a counted lenient parse;
// a failed decompression or a decompressed-size overflow owes no Close
// frame the RFC names) is measured as a counted, assessable warning
// checked against the allowlist.
//
// The traces are JSON files in testdata/deflstate/ (generated by
// model/gen/gen_deflstatetraces.py, cross-checked against the
// byte-level implementation model, the RFC 7692 7.2.1 classifier, and
// the independent nuXmv coarse encoding); the warning ledger is
// testdata/deflstate/NOTES.json, the allowlist of accepted divergences
// (each with its RFC basis and reason). The gate fails if a warning
// fires that NOTES.json does not accept, or if a NOTES.json entry no
// longer fires (stale).
//
// Only the final frame decompresses: a compressed fragment is returned
// untouched (no per-frame decompression), so the machine's mid-stream
// state is not observable at the frame level and the expectations live
// at the final frame and the ledger.

func TestMBTDeflState(t *testing.T) {
	t.Parallel()
	traces := loadTraces[mbtTrace](t, "testdata/deflstate", "MBT-deflstate")
	allowed := loadMBTNotes(t, "testdata/deflstate/NOTES.json")
	ledger := newMBTLedger()
	// The check runs after every subtest has finished (parallel subtests
	// complete before the parent's cleanup).
	t.Cleanup(func() { checkMBTWarnings(t, ledger, allowed) })
	for _, tr := range traces {
		t.Run(tr.ID, func(t *testing.T) {
			t.Parallel()
			runMBTTrace(t, tr, ledger, true)
		})
	}
}
