package ws

// Model-based validation suite: replays the traces generated from the
// frame-reassembly formal model (model/, doc/STATES.md) against a live
// RawConn. It asserts the MUST protocol outcomes hard, and measures the
// SHOULD / MAY layer of RFC 6455 7.1.7 as a counted, assessable warning
// ledger, so the suite pins conformance (not merely a behavior snapshot)
// and the divergences can be tracked and driven to zero.
//
// Each trace is a JSON file in testdata/mbt/ (generated by model/gen,
// committed, deterministic). A trace carries:
//   - frames:    the peer's frames as concrete bytes (side-specific masking
//     already applied),
//   - events:    the MUST-delivered ReadEvent results,
//   - terminal:  the close-frame outcomes for a terminal step. Each outcome
//     has a modality: must (hard), should (the RFC recommendation), or may
//     (a permitted deviation). Which outcome the implementation actually
//     takes is what the trace measures; taking a may outcome records a
//     warning.
//
// Warnings are aggregated by a stable ID, checked against testdata/mbt/
// NOTES.json (the allowlist of accepted divergences, each with a reason),
// and reported as a single countable line. The gate fails if a warning
// fires that NOTES.json does not accept, or if a NOTES.json entry no longer
// fires (stale). Regenerate the traces with `make mbt-gen`.

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"testing"
)

type mbtTrace struct {
	ID             string       `json:"id"`
	Machine        string       `json:"machine"`
	Side           string       `json:"side"`
	MaxMessageSize int64        `json:"maxMessageSize"`
	FromState      string       `json:"fromState"`
	Frame          string       `json:"frame"`
	Desc           string       `json:"desc"`
	RFC            []string     `json:"rfc"`
	Frames         []string     `json:"frames"`
	Events         []mbtEvent   `json:"events"`
	Terminal       *mbtTerminal `json:"terminal"`
}

type mbtEvent struct {
	Kind    string `json:"kind"` // msg | ctrl | close
	Op      string `json:"op"`
	Payload string `json:"payload"`
	Code    int    `json:"code"`
	Reason  string `json:"reason"`
}

type mbtTerminal struct {
	Outcomes []mbtOutcome `json:"outcomes"`
}

type mbtOutcome struct {
	Wire mbtWire `json:"wire"`
	Term string  `json:"term"` // eof | closeErr | proto
	Mod  string  `json:"mod"`  // must | should | may
	Code int     `json:"code"`
	ID   string  `json:"id"`
	Note string  `json:"note"`
}

type mbtWire struct {
	Kind string `json:"kind"` // none | empty | coded
	Code int    `json:"code"`
}

// loadTraces reads and parses every committed trace JSON in dir. Both MBT
// machines store traces the same way — one JSON object per file in a testdata
// dir, with NOTES.json as the sidecar ledger rather than a trace — so they
// share one loader over the trace struct each machine defines.
func loadTraces[T any](t *testing.T, dir, label string) []T {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read %s: %v", dir, err)
	}
	var out []T
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") || e.Name() == "NOTES.json" {
			continue
		}
		// The path is the fixed testdata dir plus a filename from its own
		// listing, never external input.
		b, err := os.ReadFile(filepath.Join(dir, e.Name())) //nolint:gosec // fixed testdata dir + own listing
		if err != nil {
			t.Fatalf("read %s: %v", e.Name(), err)
		}
		var tr T
		err = json.Unmarshal(b, &tr)
		if err != nil {
			t.Fatalf("parse %s: %v", e.Name(), err)
		}
		out = append(out, tr)
	}
	if len(out) == 0 {
		t.Fatalf("no %s traces found in %s", label, dir)
	}
	return out
}

// loadMBTNotes reads the allowlist of accepted warnings. A missing file means
// an empty allowlist (any warning that fires then fails the gate).
func loadMBTNotes(t *testing.T, path string) map[string]bool {
	t.Helper()
	// A fixed testdata path, never external input.
	b, err := os.ReadFile(path) //nolint:gosec // fixed testdata path
	if err != nil {
		if os.IsNotExist(err) {
			return map[string]bool{}
		}
		t.Fatalf("read %s: %v", path, err)
	}
	var notes []struct {
		ID string `json:"id"`
	}
	err = json.Unmarshal(b, &notes)
	if err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	m := make(map[string]bool, len(notes))
	for _, n := range notes {
		m[n.ID] = true
	}
	return m
}

func TestMBTReassembly(t *testing.T) {
	t.Parallel()
	traces := loadTraces[mbtTrace](t, "testdata/mbt", "MBT")
	allowed := loadMBTNotes(t, "testdata/mbt/NOTES.json")
	ledger := newMBTLedger()
	// The check runs after every subtest has finished (parallel subtests
	// complete before the parent's cleanup).
	t.Cleanup(func() { checkMBTWarnings(t, ledger, allowed) })
	for _, tr := range traces {
		t.Run(tr.ID, func(t *testing.T) {
			t.Parallel()
			runMBTTrace(t, tr, ledger)
		})
	}
}

func runMBTTrace(t *testing.T, tr mbtTrace, ledger *mbtLedger) {
	t.Helper()
	var data []byte
	for _, h := range tr.Frames {
		b, err := hex.DecodeString(h)
		if err != nil {
			t.Fatalf("%s: bad frame hex %q: %v", tr.ID, h, err)
		}
		data = append(data, b...)
	}

	isClient := tr.Side == "client"
	fc := &fakeConn{data: data}
	c := newRawConn(fc, fc, isClient, tr.MaxMessageSize, 0, 0)

	// MUST: the delivered events, in order.
	for i, exp := range tr.Events {
		ev, err := c.ReadEvent()
		checkMBTEvent(t, tr.ID, i, exp, ev, err)
	}

	// Terminal step: a terminal error is returned (MUST), and the close-frame
	// behavior must match one of the modeled outcomes (MUST/SHOULD/MAY).
	if tr.Terminal != nil {
		_, err := c.ReadEvent()
		if err == nil {
			t.Fatalf("%s: want terminal error, got nil", tr.ID)
		}
		kind, code := mbtTerminalKind(err)
		wireKind, wireCode := decodeMBTWire(t, tr.ID, fc.written, isClient)
		resolveMBTOutcome(t, tr.ID, tr.Terminal.Outcomes, kind, code, wireKind, wireCode, ledger)
	}
}

func mbtOp(s string) Op {
	switch s {
	case "text":
		return OpText
	case "binary":
		return OpBinary
	case "ping":
		return OpPing
	case "pong":
		return OpPong
	}
	panic("unknown op " + s)
}

func checkMBTEvent(t *testing.T, id string, i int, exp mbtEvent, ev Event, err error) {
	t.Helper()
	if err != nil {
		t.Fatalf("%s event[%d]: want event, got error %v", id, i, err)
	}
	switch exp.Kind {
	case "msg":
		if ev.Op != mbtOp(exp.Op) {
			t.Fatalf("%s event[%d]: msg op = %d, want %s", id, i, ev.Op, exp.Op)
		}
		want, _ := hex.DecodeString(exp.Payload)
		if !bytes.Equal(ev.Payload, want) {
			t.Fatalf("%s event[%d]: msg payload = % x, want %s", id, i, ev.Payload, exp.Payload)
		}
	case "ctrl":
		if ev.Op != mbtOp(exp.Op) {
			t.Fatalf("%s event[%d]: ctrl op = %d, want %s", id, i, ev.Op, exp.Op)
		}
	case "close":
		if ev.Op != OpClose || ev.Code != exp.Code || ev.Reason != exp.Reason {
			t.Fatalf("%s event[%d]: close = (op=%d code=%d reason=%q), want (code=%d reason=%q)",
				id, i, ev.Op, ev.Code, ev.Reason, exp.Code, exp.Reason)
		}
	default:
		t.Fatalf("%s event[%d]: unknown kind %q", id, i, exp.Kind)
	}
}

// mbtTerminalKind classifies a terminal error: eof, a coded close, or a bare
// protocol error (the message-level violation that carries no close code).
func mbtTerminalKind(err error) (string, int) {
	if errors.Is(err, io.EOF) {
		return "eof", 0
	}
	var ce *CloseError
	if errors.As(err, &ce) {
		return "closeErr", ce.Code
	}
	return "proto", 0
}

// decodeMBTWire decodes the close frame the machine wrote, classifying it as
// none (no frame), empty (a close frame with no code), or coded (with a code).
// It also enforces the masking rule: a client masks its writes, a server does
// not (RFC 6455 5.1).
func decodeMBTWire(t *testing.T, id string, written []byte, isClient bool) (string, int) {
	t.Helper()
	if len(written) == 0 {
		return "none", 0
	}
	if Op(written[0]&opcodeMask) != OpClose {
		t.Fatalf("%s: first written frame op = %d, want close", id, written[0]&opcodeMask)
	}
	masked := written[1]&0x80 != 0
	if isClient && !masked {
		t.Fatalf("%s: client close frame is not masked (% x)", id, written)
	}
	if !isClient && masked {
		t.Fatalf("%s: server close frame is masked (% x)", id, written)
	}
	off := 2
	var key [4]byte
	if masked {
		if len(written) < 6 {
			t.Fatalf("%s: masked close frame too short (% x)", id, written)
		}
		copy(key[:], written[2:6])
		off = 6
	}
	l := int(written[1] & 0x7f)
	if len(written) < off+l {
		t.Fatalf("%s: close frame payload truncated (% x)", id, written)
	}
	if l == 0 {
		return "empty", 0
	}
	payload := append([]byte(nil), written[off:off+l]...)
	if masked {
		for i := range payload {
			payload[i] ^= key[i%maskKeyLen]
		}
	}
	if len(payload) < closeCodeBytes {
		t.Fatalf("%s: close frame payload < 2 bytes (% x)", id, written)
	}
	return "coded", int(binary.BigEndian.Uint16(payload[:closeCodeBytes]))
}

// resolveMBTOutcome finds the modeled outcome matching the actual terminal
// behavior and applies its modality: must/should are silent (conformant),
// may records a warning to assess. An outcome matching none of the modeled
// options is a model/implementation disagreement and fails the test.
func resolveMBTOutcome(t *testing.T, id string, outcomes []mbtOutcome, term string,
	code int, wireKind string, wireCode int, ledger *mbtLedger) {
	t.Helper()
	for _, o := range outcomes {
		if o.Term != term {
			continue
		}
		if term == "closeErr" && o.Code != code {
			continue
		}
		switch o.Wire.Kind {
		case "none":
			if wireKind != "none" {
				continue
			}
		case "empty":
			if wireKind != "empty" {
				continue
			}
		case "coded":
			if wireKind != "coded" || wireCode != o.Wire.Code {
				continue
			}
		default:
			t.Fatalf("%s: unknown wire kind %q", id, o.Wire.Kind)
		}
		switch o.Mod {
		case "must", "should":
			return
		case "may":
			ledger.add(o.ID, id, o.Note)
			return
		default:
			t.Fatalf("%s: unknown modality %q", id, o.Mod)
		}
	}
	t.Fatalf("%s: actual (term=%s code=%d wire=%s/%d) matches no modeled outcome", id, term, code, wireKind, wireCode)
}

// mbtWarning is one instance of an assessed divergence (a MAY outcome taken
// instead of the SHOULD).
type mbtWarning struct {
	ID    string
	Trace string
	Note  string
}

type mbtLedger struct {
	mu    sync.Mutex
	items []mbtWarning
}

func newMBTLedger() *mbtLedger { return &mbtLedger{} }

func (l *mbtLedger) add(id, trace, note string) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.items = append(l.items, mbtWarning{ID: id, Trace: trace, Note: note})
}

func (l *mbtLedger) snapshot() []mbtWarning {
	l.mu.Lock()
	defer l.mu.Unlock()
	return append([]mbtWarning(nil), l.items...)
}

// checkMBTWarnings enforces the allowlist and reports the countable summary.
// It fails if a warning fires that NOTES.json does not accept (a new,
// unassessed divergence) or if a NOTES.json entry no longer fires (stale —
// the divergence was eliminated, so remove the entry). The goal is a ledger
// that shrinks to empty as the implementation converges on the SHOULDs.
func checkMBTWarnings(t *testing.T, ledger *mbtLedger, allowed map[string]bool) {
	t.Helper()
	items := ledger.snapshot()
	counts := make(map[string]int)
	perID := make(map[string][]string)
	for _, w := range items {
		counts[w.ID]++
		perID[w.ID] = append(perID[w.ID], w.Trace)
	}
	for id := range counts {
		if !allowed[id] {
			t.Errorf("%d warning(s) %q are not accepted in NOTES.json (e.g. %s)",
				counts[id], id, strings.Join(perID[id], ", "))
		}
	}
	for id := range allowed {
		if counts[id] == 0 {
			t.Errorf("NOTES.json entry %q is stale (no trace fires it; remove it)", id)
		}
	}
	if len(counts) == 0 {
		t.Log("MBT-WARNINGS: 0 (fully conformant to the SHOULD layer)")
		return
	}
	keys := make([]string, 0, len(counts))
	for k := range counts {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var parts []string
	for _, id := range keys {
		parts = append(parts, fmt.Sprintf("%s x%d", id, counts[id]))
	}
	t.Logf("MBT-WARNINGS: %d total, %d distinct: %s", len(items), len(counts), strings.Join(parts, " | "))
}
