package ws

import "testing"

// TestMBTDeflate replays the committed RSV1 / compressed-message traces
// (model/, doc/DEFLATE-MACHINE.md) against a live RawConn with
// permessage-deflate negotiated. Same contract as TestMBTReassembly: the
// MUST protocol outcomes are asserted hard, and the SHOULD / MAY layer of
// the RFC 7692 silences (a failed decompression owes no Close frame the
// RFC names; a decompressed size overflow likewise) is measured as a
// counted, assessable warning checked against the allowlist.
//
// The traces are JSON files in testdata/deflate/ (generated by
// model/gen, cross-checked against the independent nuXmv encoding); the
// warning ledger is testdata/deflate/NOTES.json, the allowlist of
// accepted divergences (each with its RFC basis and reason). The gate
// fails if a warning fires that NOTES.json does not accept, or if a
// NOTES.json entry no longer fires (stale).

func TestMBTDeflate(t *testing.T) {
	t.Parallel()
	traces := loadTraces[mbtTrace](t, "testdata/deflate", "MBT-deflate")
	allowed := loadMBTNotes(t, "testdata/deflate/NOTES.json")
	ledger := newMBTLedger()
	// The check runs after every subtest has finished (parallel subtests
	// complete before the parent's cleanup).
	t.Cleanup(func() { checkMBTWarnings(t, ledger, allowed) })
	for _, tr := range traces {
		t.Run(tr.ID, func(t *testing.T) {
			t.Parallel()
			runMBTTrace(t, tr, ledger, true)
		})
	}
}
