package ws

// Model-based validation suite for the close-handshake machine: replays the
// traces generated from the RFC 6455 close-handshake formal model (model/gen/
// closehandshake.py, doc/CLOSE-HANDSHAKE.md) against a live RawConn. The model
// is derived purely from the RFC (Section 5.5.1, 7.1.1-7.1.7, 7.4, 8.1); this
// runner is where the implementation is observed and checked against it.
//
// Each trace is a JSON file in testdata/closehandshake/ (generated by
// model/gen, committed, deterministic). A trace carries one (state, shape):
// the RFC state (OPEN / CLOSING / CLOSED) and the peer's Close body shape.
// OPEN traces start on a live connection; CLOSING and CLOSED traces first
// close with initCode (a write reaching the RFC's CLOSING/CLOSED state), then
// feed the peer's Close.
//
// The suite checks the RFC's close-handshake obligations:
//   - MUST NOT put a must-not-set code (1004/1005/1006/1015) on the wire (7.4);
//   - OPEN: MUST answer a received Close (5.5.1), SHOULD echo its code (5.5.1),
//     MUST resolve to the received code (7.1.5);
//   - OPEN on an invalid Close: MUST fail (7.1.7), SHOULD send 1002 (7.1.7),
//     MAY omit it (7.1.7);
//   - CLOSING: MUST NOT send a second Close (5.5.1); SHOULD resolve to the
//     peer's Close -- the first Close received -- and close once both have been
//     sent and received (7.1.2, 7.1.5);
//   - CLOSED: absorbing, no reaction.
//
// A MUST mismatch fails the test. A SHOULD/MAY the implementation does not
// meet is a counted, assessable warning, aggregated by a stable ID, checked
// against testdata/closehandshake/NOTES.json (the allowlist of accepted
// divergences). Regenerate the traces with `make close-mbt-gen`.

import (
	"encoding/hex"
	"errors"
	"io"
	"testing"
)

type closeTrace struct {
	ID         string         `json:"id"`
	Machine    string         `json:"machine"`
	Side       string         `json:"side"`
	State      string         `json:"state"`
	Shape      string         `json:"shape"`
	InitCode   *int           `json:"initCode"`
	Desc       string         `json:"desc"`
	RFC        []string       `json:"rfc"`
	Frames     []string       `json:"frames"`
	Resolution int            `json:"resolution"`
	Dispo      string         `json:"disposition"`
	Outcomes   []closeOutcome `json:"outcomes"`
}

type closeOutcome struct {
	Wire       string `json:"wire"` // none | empty | coded
	Code       *int   `json:"code"`
	Dispo      string `json:"disposition"`
	Resolution *int   `json:"resolution"`
	Mod        string `json:"mod"` // must | should | may
	ID         string `json:"id"`
	Note       string `json:"note"`
}

func TestMBTCloseHandshake(t *testing.T) {
	t.Parallel()
	traces := loadTraces[closeTrace](t, "testdata/closehandshake", "close-handshake")
	allowed := loadMBTNotes(t, "testdata/closehandshake/NOTES.json")
	ledger := newMBTLedger()
	t.Cleanup(func() { checkMBTWarnings(t, ledger, allowed) })
	for _, tr := range traces {
		t.Run(tr.ID, func(t *testing.T) {
			t.Parallel()
			runCloseTrace(t, tr, ledger)
		})
	}
}

// mustNotSetCode is the RFC 6455 7.4 set that MUST NOT appear as a status code
// in a Close frame payload: 1004 (reserved), 1005/1006/1015.
func mustNotSetCode(c int) bool {
	switch c {
	case 1004, StatusNoStatusReceived, StatusAbnormalClosure, closeCodeTLSFailure:
		return true
	}
	return false
}

func runCloseTrace(t *testing.T, tr closeTrace, ledger *mbtLedger) {
	t.Helper()
	var data []byte
	for _, h := range tr.Frames {
		b, err := hex.DecodeString(h)
		if err != nil {
			t.Fatalf("%s: bad frame hex %q: %v", tr.ID, h, err)
		}
		data = append(data, b...)
	}
	// A large limit so no close frame is size-rejected: maxMessageSize is a
	// harness parameter, not an RFC concept, so it is not part of the model.
	fc := &fakeConn{data: data}
	isClient := tr.Side == "client"
	c := newRawConn(fc, fc, isClient, 1<<20, 0, 0)

	// CLOSING / CLOSED: start the closing handshake (a write) before feeding
	// the peer's Close. Shutdown leaves the transport up, so the peer's Close
	// that follows is read, not skipped.
	initLen := 0
	if tr.InitCode != nil {
		_ = c.Shutdown(*tr.InitCode, "")
		if tr.State == "CLOSED" {
			// Reach CLOSED for real: with the transport down, the Close fed
			// below must find the absorbing state (§7.1.4) and not react.
			_ = c.Close()
		}
		initLen = len(fc.written)
	}

	// Read until the connection is terminal, collecting any delivered events.
	var events []Event
	var termErr error
	for {
		ev, err := c.ReadEvent()
		if err != nil {
			termErr = err

			break
		}
		events = append(events, ev)
	}
	// The RFC's last step: the transport teardown after the reads are done.
	_ = c.Close()

	// The response wire is any Close the implementation wrote after the
	// initiation (OPEN: the whole write buffer; CLOSING/CLOSED: the delta).
	respWire := fc.written[initLen:]
	wireKind, wireCode := decodeMBTWire(t, tr.ID, respWire, isClient)
	res := observedResolution(events, termErr)

	checkCloseOutcome(t, tr, ledger, wireKind, wireCode, res)
}

// observedResolution is the Connection Close Code the implementation reports:
// the delivered Close event's code when one is delivered (OPEN on a
// well-formed Close), else the terminal's code (a *CloseError's code, or the
// clean 1000 for an io.EOF terminal).
func observedResolution(events []Event, termErr error) int {
	for _, ev := range events {
		if ev.Op == OpClose {
			return ev.Code
		}
	}
	var ce *CloseError
	if termErr != nil && errors.As(termErr, &ce) {
		return ce.Code
	}
	if termErr != nil && errors.Is(termErr, io.EOF) {
		return StatusNormalClosure
	}
	return 0
}

func checkCloseOutcome(t *testing.T, tr closeTrace, ledger *mbtLedger, wireKind string, wireCode, res int) {
	t.Helper()
	// The MUST NOT (all states): a must-not-set code never reaches the wire.
	if wireKind == "coded" && mustNotSetCode(wireCode) {
		t.Fatalf("%s: RFC 6455 7.4 MUST NOT -- a must-not-set code %d on the wire", tr.ID, wireCode)
	}
	switch tr.State {
	case "OPEN":
		checkOpen(t, tr, ledger, wireKind, wireCode, res)
	case "CLOSING":
		checkClosing(t, tr, ledger, wireKind, wireCode, res)
	case "CLOSED":
		checkClosed(t, tr, wireKind, wireCode)
	default:
		t.Fatalf("%s: unknown state %q", tr.ID, tr.State)
	}
}

func checkOpen(t *testing.T, tr closeTrace, ledger *mbtLedger, wireKind string, wireCode, res int) {
	t.Helper()
	// OPEN on an invalid Close has two permitted outcomes (SHOULD 1002, MAY
	// omit); OPEN on a well-formed Close has one.
	if tr.Dispo == "failed" {
		checkOpenInvalid(t, tr, ledger, wireKind, wireCode, res)
		return
	}
	// Well-formed Close: MUST answer, SHOULD echo the code, MUST resolve.
	o := tr.Outcomes[0]
	if wireKind == "none" {
		t.Fatalf("%s: RFC 6455 5.5.1 MUST -- no Close sent in response to the peer's Close", tr.ID)
	}
	if o.Code != nil {
		// A code-bearing response: the echoed code is a SHOULD (5.5.1).
		if wireKind != "coded" || wireCode != *o.Code {
			ledger.add("SHOULD:close-echo", tr.ID, "RFC 6455 5.5.1 SHOULD: echo the status code received")
		}
	} else {
		// The 1005 (no-status) case: the response carries no code (7.4).
		if wireKind != "empty" {
			ledger.add("SHOULD:close-echo", tr.ID, "RFC 6455 5.5.1 SHOULD: the no-status Close carries an empty body")
		}
	}
	if o.Resolution != nil && res != *o.Resolution {
		t.Fatalf("%s: RFC 6455 7.1.5 MUST -- resolution %d, want %d", tr.ID, res, *o.Resolution)
	}
}

func checkOpenInvalid(t *testing.T, tr closeTrace, ledger *mbtLedger, wireKind string, wireCode, res int) {
	t.Helper()
	// 7.1.7: MUST close (the terminal is reached -- guaranteed by the driver);
	// SHOULD send a Close with 1002; MAY omit it. The peer's invalid code is
	// never echoed.
	switch {
	case wireKind == "coded" && wireCode == StatusProtocolError:
		// The SHOULD is met: no warning.
	case wireKind == "none":
		ledger.add("MAY:close-omit", tr.ID, "RFC 6455 7.1.7 MAY: omit the Close on a protocol failure")
	case wireKind == "coded":
		if wireCode < StatusNormalClosure || wireCode > 4999 {
			t.Fatalf("%s: RFC 6455 7.1.7 MUST NOT -- an undefined/out-of-range code %d on the wire", tr.ID, wireCode)
		}
		ledger.add("SHOULD:close-717", tr.ID, "RFC 6455 7.1.7 SHOULD: the protocol-failure Close carries 1002")
	default: // empty
		ledger.add("SHOULD:close-717", tr.ID, "RFC 6455 7.1.7 SHOULD: the protocol-failure Close carries 1002")
	}
	// The failure resolves to 1002, never the peer's invalid code (7.4/7.4.2).
	if res != StatusProtocolError {
		t.Fatalf("%s: RFC 6455 7.1.7 -- the invalid Close must resolve to 1002, got %d", tr.ID, res)
	}
}

func checkClosing(t *testing.T, tr closeTrace, ledger *mbtLedger, wireKind string, wireCode, res int) {
	t.Helper()
	// We already sent a Close, so a second Close is a protocol error: the
	// response frame must be absent (5.5.1).
	if wireKind != "none" {
		t.Fatalf("%s: RFC 6455 5.5.1 -- a second Close sent after initiating the handshake (wire=%s/%d)",
			tr.ID, wireKind, wireCode)
	}
	// 7.1.2 / 7.1.5: once both sent and received, close resolving to the
	// peer's Close (the first Close received). The implementation resolving to
	// its own sent code (and never reading the peer's Close) is the 7.1.2
	// SHOULD finding -- a counted, assessable warning, not a MUST failure.
	if tr.Resolution != res {
		ledger.add("SHOULD:close-712", tr.ID,
			"RFC 6455 7.1.2 SHOULD: close once both sent and received, resolving to the first Close received (7.1.5)")
	}
}

func checkClosed(t *testing.T, tr closeTrace, wireKind string, wireCode int) {
	t.Helper()
	// CLOSED is absorbing (7.1.4): a received Close is not processed, so no
	// response frame is written.
	if wireKind != "none" {
		t.Fatalf("%s: RFC 6455 7.1.4 -- CLOSED is absorbing, but a Close was written (wire=%s/%d)", tr.ID, wireKind, wireCode)
	}
}
